### ISSUE TITLE
Failed to create docx file

### ISSUE THREAD

**Issue by ibmer921150** [typhoon-hil/allure-docx#17] opened 2018-07-06 01:28 UTC
Env: Ubuntu17.10
Python: 3.6
pip3

# allure-docx allure-results/ allure-general.docx

Template: /usr/local/lib/python3.6/dist-packages/allure_docx/template.docx
Traceback (most recent call last):
  File "/usr/local/bin/allure-docx", line 11, in <module>
    load_entry_point('allure-docx==0.2.0', 'console_scripts', 'allure-docx')()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/allure_docx/commandline.py", line 46, in main
    process.run(alluredir, template, output, title, logo, logo_height, detail_level)
  File "/usr/local/lib/python3.6/dist-packages/allure_docx/process.py", line 302, in run
    create_docx(results, session, template_path, output_filename, title, logo_path, logo_height, detail_level)
  File "/usr/local/lib/python3.6/dist-packages/allure_docx/process.py", line 260, in create_docx
    hdr_cells[0].add_paragraph(test['statusDetails']['trace']+'\n', style='Code')
KeyError: 'trace'

**Comment by Sup3rGeo** [comment] 2018-07-08 11:44
@ibmer921150 thanks for the report! I am closing as it seems to be duplicate of #16.

**Closed by Sup3rGeo** 2018-07-08 11:44 UTC

**Comment by Sup3rGeo** [comment] 2018-07-08 11:48
@ibmer921150 could you please also provide an example test result so I can test it?
